{
    'name': 'efundOpc',
    'version': '19.0.1',
    'category': 'Finance',
    'summary': 'Gestion de Fonds - Suite',
    'description': """
    Module de gestion des fonds d'investissement
    Gestion complète des fonds communs de placement
    ===========================================

    Fonctionnalités principales:
    * Gestion des sociétés de gestion
    * Gestion des fonds avec multi-sociétés
    * Suivi des performances
    * Gestion des investisseurs
    * Reporting réglementaire
""",
    'author': 'eSecureX',
    'website': 'https://www.esecurex.com',
    'depends': ['base', 'account', 'contacts', 'web'],
    'data': [
        'security/ir.model.access.csv',
        'security/efund_security.xml',
        #'views/efund_views_management_company_form.xml',
        'views/efund_management_compagny_views.xml',
        'views/efund_action_menu_principal.xml',
        'views/efund_menu_principal.xml',
        'views/efund_action_menu_parametre.xml',
        'views/efund_views_kyc_document.xml',
        'views/efund_aml_alert_views.xml',
        'views/efund_fund_instrument_views.xml',
        'wizard/efund_bon_amortization_wizard.xml',
        'wizard/efund_instrument_import_price_wizard_views.xml',
        'views/efund_vehicule_instrument_core_price_views.xml',
        'views/efund_position_views.xml',
        'wizard/efund_position_wizard_views.xml',
        #'views/efund_investor_subscription_views.xml',
        'views/efund_investor_subscription_news_views.xml',
        'wizard/efund_bourse_order_execution_wizard_views.xml',
        'views/efund_bourse_order_views.xml',
        'views/efund_depositaire.xml',
        'views/efund_investor_cash_operation_views.xml',
        'views/efund_event_type_view.xml',
        # 'views/efund_menu_parametre.xml',
        'views/efund_fund_investor_views.xml',
        #'views/efund_investor_views_news.xml',
        'views/efund_investor_news_views.xml',
        #'views/efund_investor_views.xml',
        'views/efund_views_parametre.xml',
        # 'views/efund_fund_views.xml',
        # 'views/view_efund_initial_valuation_investor_line_form.xml',
        # 'views/fund_initial_valuation_wizard_views.xml',
        # 'views/efund_share_class_views.xml',
        'views/efund_view_compliance_policy_tree.xml',
        'views/efund_views_valuation.xml',
        'reports/efund_kyc_report.xml',
        'reports/efund_kyc_report_template.xml',
        'views/efund_fund_instrument_event_views.xml',
        'views/efund_position_adjustment_views.xml',
        #'views/efund_mandate_views.xml',
        'wizard/efund_mandate_termination_wizard_views.xml',
        #'views/efund_investor_deposit_views.xml',
        'views/efund_investor_redemption_views.xml',
        #'views/efund_investor_withdraw_views.xml',
        'wizard/efund_confirm_wizard_views.xml',
        'views/efund_fund_type_views.xml',
        'views/efund_asset_class_views.xml',
        'views/efund_reconciliation_log_views.xml',
        'wizard/efund_investor_portfolio_report_views.xml',
        'reports/efund_investor_portfolio_report.xml',
        'views/efund_fund_prudential_limit_views.xml',
        'views/efund_fund_prudential_ratio_views.xml',
        'views/efund_fund_share_class.xml',
        'views/efund_fund_instrument_transactions_views.xml',
        'views/efund_investment_transaction.xml',
        'views/efund_fund_instrument_dat_views.xml',
        'views/efund_instrument_core_views.xml',
        'reports/efund_investor_kyc.xml',
        'views/efund_vehicule_fund_views.xml',
        'views/efund_fund_expenses_views.xml',

        'views/efund_fund_instrument_equity_views.xml',
        'views/efund_investment_order.xml',
        'views/efund_vehicule_mandat.xml',
        'views/efund_country_zone_views.xml',
        'views/efund_vehicule_instrument_fee_rule_views.xml',
        'views/efund_fund_instrument_opcvm_views.xml',
        'views/efund_accounting_schema.xml',
        'views/efund_view_issuer.xml',
        'views/efund_vehicule_cash_operation_views.xml',
        'views/efund_accounting_event.xml',
        'wizard/efund_investor_join_fund_wizard_views.xml',
        'views/efund_codification_account_number.xml',
        'views/efund_market_fee_config_views.xml',
        'views/efund_public_holiday_view.xml',
        'data/sequence.xml',
        'wizard/bond_simulation_wizard_view.xml',
        'wizard/efund_vehicule_mandat_deposit_wizard_views.xml',
        #'data/opcvm_complete_chart_template.xml',

    ],

    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
