# -*- coding: utf-8 -*-
from odoo import models, fields, api, _
from datetime import date
from odoo.exceptions import ValidationError
import base64
import io
from openpyxl import Workbook

class FundReportRegulatory(models.Model):
    _name = 'efund.fund.report.regulatory'
    _description = 'Regulatory Report of Fund'
    _order = 'report_date desc'

    name = fields.Char(string="Report Reference", required=True, copy=False, default=lambda self: _('New'))
    fund_id = fields.Many2one('efund.fund', string="Fund", required=True, ondelete='cascade')
    company_id = fields.Many2one('res.company', string="Management Company", required=True, default=lambda self: self.env.company)
    report_type = fields.Selection([
        ('mensuel', 'Monthly Report'),
        ('trimestriel', 'Quarterly Report'),
        ('semestriel', 'Semi-Annual Report'),
        ('annuel', 'Annual Report'),
    ], string="Report Type", required=True, default='mensuel')
    report_date = fields.Date(string="Reporting Date", required=True, default=fields.Date.context_today)
    generated_on = fields.Datetime(string="Generated On", readonly=True)
    generated_by = fields.Many2one('res.users', string="Generated By", readonly=True)

    total_nav = fields.Monetary(string="Total NAV", currency_field='currency_id')
    total_assets = fields.Monetary(string="Total Assets", currency_field='currency_id')
    total_liabilities = fields.Monetary(string="Total Liabilities", currency_field='currency_id')
    currency_id = fields.Many2one('res.currency', string="Currency", related='fund_id.currency_id', store=True, readonly=True)

    # Compliance indicators
    ratio_liquidity = fields.Float(string="Liquidity Ratio (%)")
    ratio_concentration = fields.Float(string="Concentration Ratio (%)")
    ratio_diversification = fields.Float(string="Diversification Ratio (%)")
    ratio_coverage = fields.Float(string="Hedging Coverage (%)")
    ratio_exposure = fields.Float(string="Market Exposure (%)")

    # Attachments
    attachment_ids = fields.One2many('ir.attachment', 'res_id', domain=[('res_model', '=', 'fund.report.regulatory')], string="Attachments")

    status = fields.Selection([
        ('draft', 'Draft'),
        ('in_review', 'Under Review'),
        ('validated', 'Validated'),
        ('submitted', 'Submitted'),
        ('archived', 'Archived'),
    ], string="Status", default='draft')

    notes = fields.Text(string="Notes / Comments")
    reviewer_id = fields.Many2one('res.users', string="Reviewer")
    validated_on = fields.Datetime(string="Validated On")

    # Exported File
    export_file = fields.Binary(string="Exported File", readonly=True)
    export_filename = fields.Char(string="Export Filename")

    @api.constrains('ratio_liquidity', 'ratio_concentration', 'ratio_diversification')
    def _check_ratios(self):
        for rec in self:
            if rec.ratio_liquidity < 0 or rec.ratio_liquidity > 100:
                raise ValidationError(_("Liquidity ratio must be between 0 and 100."))
            if rec.ratio_concentration < 0 or rec.ratio_concentration > 100:
                raise ValidationError(_("Concentration ratio must be between 0 and 100."))

    @api.model
    def create(self, vals):
        if vals.get('name', _('New')) == _('New'):
            seq = self.env['ir.sequence'].next_by_code('fund.report.regulatory') or _('New')
            vals['name'] = seq
        vals['generated_by'] = self.env.user.id
        vals['generated_on'] = fields.Datetime.now()
        return super().create(vals)

    def action_submit(self):
        for rec in self:
            rec.status = 'submitted'

    def action_validate(self):
        for rec in self:
            rec.status = 'validated'
            rec.validated_on = fields.Datetime.now()

    def action_export_excel(self):
        """Export regulatory report to Excel"""
        for rec in self:
            wb = Workbook()
            ws = wb.active
            ws.title = "Regulatory Report"

            ws.append(["Report Reference", rec.name])
            ws.append(["Fund", rec.fund_id.name])
            ws.append(["Report Type", rec.report_type])
            ws.append(["Reporting Date", rec.report_date.strftime('%Y-%m-%d')])
            ws.append([])
            ws.append(["Financial Data"])
            ws.append(["Total NAV", rec.total_nav])
            ws.append(["Total Assets", rec.total_assets])
            ws.append(["Total Liabilities", rec.total_liabilities])
            ws.append([])
            ws.append(["Compliance Ratios"])
            ws.append(["Liquidity Ratio (%)", rec.ratio_liquidity])
            ws.append(["Concentration Ratio (%)", rec.ratio_concentration])
            ws.append(["Diversification Ratio (%)", rec.ratio_diversification])
            ws.append(["Market Exposure (%)", rec.ratio_exposure])
            ws.append(["Hedging Coverage (%)", rec.ratio_coverage])

            output = io.BytesIO()
            wb.save(output)
            output.seek(0)
            file_content = output.read()
            output.close()

            rec.export_file = base64.b64encode(file_content)
            rec.export_filename = f"{rec.name}_report.xlsx"

            return {
                'type': 'ir.actions.act_url',
                'url': f'/web/content/{rec.id}?model=fund.report.regulatory&field=export_file&filename_field=export_filename&download=true',
                'target': 'self',
            }
